// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class BillDetail
{
    public int Id { get; set; }

    public int BillId { get; set; }

    public string MemberName { get; set; }

    public decimal Amount { get; set; }

    public bool Paid { get; set; }

    public virtual Bill Bill { get; set; }
}