// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TravelLog.Models
{
    public partial class get_SerialNumberResult
    {
        public int SB_Serial { get; set; }
        [StringLength(10)]
        public string SB_SystemCode { get; set; }
        [StringLength(50)]
        public string SB_SystemName { get; set; }
        [StringLength(50)]
        public string SB_SerialNumber { get; set; }
        public int SB_Count { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}
