// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class ItineraryGroup
{
    /// <summary>
    /// ID
    /// </summary>
    public int ItineraryGroupId { get; set; }

    /// <summary>
    /// 行程ID
    /// </summary>
    public int ItineraryGroupItineraryId { get; set; }

    /// <summary>
    /// 使用者信箱
    /// </summary>
    public string ItineraryGroupUserEmail { get; set; }
}