// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class ItineraryDetail
{
    /// <summary>
    /// ID
    /// </summary>
    public int ItineraryDetailId { get; set; }

    /// <summary>
    /// 外鍵
    /// </summary>
    public int ItineraryId { get; set; }

    /// <summary>
    /// 第幾天
    /// </summary>
    public int ItineraryDetailDay { get; set; }

    /// <summary>
    /// 住宿 關聯 ProductType_ID
    /// </summary>
    public int ItineraryDetailAccommodation { get; set; }

    /// <summary>
    /// 商品類別 關聯 ProductType_ID
    /// </summary>
    public int ItineraryDetailProductTypeId { get; set; }

    /// <summary>
    /// 地點 關聯 Map_ID
    /// </summary>
    public int ItineraryDetailMapId { get; set; }

    /// <summary>
    /// 群組
    /// </summary>
    public int ItineraryDetailGroup { get; set; }

    /// <summary>
    /// 行程起始時間
    /// </summary>
    public DateTime ItineraryDetailStartDate { get; set; }

    /// <summary>
    /// 行程結束時間
    /// </summary>
    public DateTime ItineraryDetailEndDate { get; set; }

    /// <summary>
    /// 行程備註
    /// </summary>
    public string ItineraryDetailMemo { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    public DateTime? ItineraryDetailCreateDate { get; set; }
}