// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public DateTime OrderTime { get; set; }

    public decimal OrderTotalAmount { get; set; }

    public DateTime? DeleteAt { get; set; }

    public int UserId { get; set; }

    public int? OrderStatus { get; set; }

    public virtual OrderStatus OrderStatusNavigation { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}