// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class OrderStatus
{
    public int OsId { get; set; }

    public string OsOrderStatus { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}