// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class Payment
{
    /// <summary>
    /// 付款 ID
    /// </summary>
    public int PaymentId { get; set; }

    /// <summary>
    /// 付款成功時間（成功付款才有值）
    /// </summary>
    public DateTime? PaymentTime { get; set; }

    /// <summary>
    /// 付款方式
    /// </summary>
    public int PaymentMethod { get; set; }

    /// <summary>
    /// 綠界回傳付款方式
    /// </summary>
    public int? PaymentMethodName { get; set; }

    /// <summary>
    /// 關聯的訂單
    /// </summary>
    public int OrderId { get; set; }

    /// <summary>
    /// 付款狀態
    /// </summary>
    public int PaymentStatusId { get; set; }

    /// <summary>
    /// 綠界交易編號
    /// </summary>
    public string EcpayTransactionId { get; set; }

    public virtual Order Order { get; set; }

    public virtual PaymentMethod PaymentMethodNavigation { get; set; }

    public virtual PaymentStatus PaymentStatus { get; set; }
}