// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class PaymentMethod
{
    public int PmId { get; set; }

    public string PaymentMethod1 { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}