// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class PlaceImage
{
    public int Id { get; set; }

    public int? PlaceId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Place Place { get; set; }
}