// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class ProductTicket
{
    public int? OrderId { get; set; }

    public int? TicketId { get; set; }

    public int? ProductId { get; set; }

    public virtual Order Order { get; set; }
}