// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class Ticket
{
    public int TicketsId { get; set; }

    public string TicketsName { get; set; }

    public string TicketsType { get; set; }

    public int Price { get; set; }

    public bool IsAvailable { get; set; }

    public string Description { get; set; }

    public string RefundPolicy { get; set; }

    public DateTime? CreatedAt { get; set; }
}