// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class TourBundle
{
    public int Id { get; set; }

    public string EventName { get; set; }

    public string StartingPoint { get; set; }

    public string Destination { get; set; }

    public DateTime FirstDate { get; set; }

    public DateTime LastDate { get; set; }

    public int Duration { get; set; }

    public int Price { get; set; }

    public string EventDescription { get; set; }

    public int? Ratings { get; set; }

    public string ContactInfo { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}