// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLog.Models;

public partial class User
{
    /// <summary>
    /// ID
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// 使用者姓名
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// 信箱
    /// </summary>
    public string UserEmail { get; set; }

    /// <summary>
    /// 手機
    /// </summary>
    public string UserPhone { get; set; }

    /// <summary>
    /// 啟用狀態  0 = 啟用, 1 = 關閉 
    /// </summary>
    public bool UserEnabled { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    public DateTime UserCreateDate { get; set; }

    public virtual ICollection<UserPd> UserPds { get; set; } = new List<UserPd>();
}