// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class Bill
{
    public int Id { get; set; }

    public string Title { get; set; }

    public decimal TotalAmount { get; set; }

    public string PaidBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<BillDetail> BillDetails { get; set; } = new List<BillDetail>();
}