// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class ExternalLogin
{
    public int ExternalLoginId { get; set; }

    public string Provider { get; set; }

    public string ProviderUserId { get; set; }

    public int MiMemberId { get; set; }

    public DateTime DateCreated { get; set; }

    public virtual MemberInformation MiMember { get; set; }
}