// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class Itinerary
{
    /// <summary>
    /// 行程 ID
    /// </summary>
    public int ItineraryId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    public DateTime ItineraryCreateDate { get; set; }

    public virtual ICollection<Bill> Bills { get; set; } = new List<Bill>();

    public virtual ICollection<ItineraryDetail> ItineraryDetails { get; set; } = new List<ItineraryDetail>();

    public virtual ICollection<ItineraryGroup> ItineraryGroups { get; set; } = new List<ItineraryGroup>();
}