// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class ItineraryGroup
{
    /// <summary>
    /// 群組 ID
    /// </summary>
    public int ItineraryGroupId { get; set; }

    /// <summary>
    /// 關聯的行程 ID
    /// </summary>
    public int ItineraryGroupItineraryId { get; set; }

    /// <summary>
    /// 使用者信箱
    /// </summary>
    public string ItineraryGroupUserEmail { get; set; }

    public virtual Itinerary ItineraryGroupItinerary { get; set; }
}