// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class Itinerary
{
    /// <summary>
    /// ID
    /// </summary>
    public int ItineraryId { get; set; }

    /// <summary>
    /// 行程名稱
    /// </summary>
    public string ItineraryTitle { get; set; }

    /// <summary>
    /// 行程地點
    /// </summary>
    public string ItineraryLocation { get; set; }

    /// <summary>
    /// 行程座標
    /// </summary>
    public string ItineraryCoordinate { get; set; }

    /// <summary>
    /// 行程圖片
    /// </summary>
    public string ItineraryImage { get; set; }

    /// <summary>
    /// 行程起始時間
    /// </summary>
    public DateTime ItineraryStartDate { get; set; }

    /// <summary>
    /// 行程結束時間
    /// </summary>
    public DateTime ItineraryEndDate { get; set; }

    /// <summary>
    /// 創建使用者
    /// </summary>
    public int? ItineraryCreateUser { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    public DateTime? ItineraryCreateDate { get; set; }

    public virtual ICollection<ItineraryPrice> ItineraryPrices { get; set; } = new List<ItineraryPrice>();

    public virtual ICollection<PlaceDetail> PlaceDetails { get; set; } = new List<PlaceDetail>();
}