// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class Location
{
    /// <summary>
    /// 地點 ID
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 會員 ID
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// 關聯的行程 ID
    /// </summary>
    public int ScheduleId { get; set; }

    /// <summary>
    /// 景點
    /// </summary>
    public string Attraction { get; set; }

    /// <summary>
    /// 日期
    /// </summary>
    public DateOnly Date { get; set; }

    public virtual Schedule Schedule { get; set; }

    public virtual User User { get; set; }
}