// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class Map
{
    /// <summary>
    /// 地點 ID
    /// </summary>
    public int MapId { get; set; }

    /// <summary>
    /// 地點名稱
    /// </summary>
    public string MapPlaceName { get; set; }

    /// <summary>
    /// 地址
    /// </summary>
    public string MapAddress { get; set; }

    /// <summary>
    /// 經度
    /// </summary>
    public double MapLongitude { get; set; }

    /// <summary>
    /// 緯度
    /// </summary>
    public double MapLatitude { get; set; }

    /// <summary>
    /// 創建時間
    /// </summary>
    public DateTime MapCreateDate { get; set; }

    public virtual ICollection<ItineraryDetail> ItineraryDetails { get; set; } = new List<ItineraryDetail>();
}