// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class MemberInformation
{
    public int MiMemberId { get; set; }

    public string MiAccountName { get; set; }

    public string MiEmail { get; set; }

    public string MiPasswordHash { get; set; }

    public DateTime? MiRegistrationDate { get; set; }

    public bool? MiIsActive { get; set; }

    public string MiEmailConfirmationToken { get; set; }
}