// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class OrderStatus
{
    /// <summary>
    /// 訂單狀態 ID
    /// </summary>
    public int OsId { get; set; }

    /// <summary>
    /// 訂單狀態
    /// </summary>
    public string OsOrderStatus { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}