// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public string MerchantTradeNo { get; set; }

    public DateTime OrderTime { get; set; }

    public decimal OrderTotalAmount { get; set; }

    public DateTime? DeleteAt { get; set; }

    /// <summary>
    /// 使用者 ID
    /// </summary>
    public int UserId { get; set; }

    public int OrderStatus { get; set; }

    public int OrderPaymentStatus { get; set; }

    public virtual PaymentStatus OrderPaymentStatusNavigation { get; set; }

    public virtual OrderStatus OrderStatusNavigation { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }
}