// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelLogAPI.Models;

public partial class PaymentStatus
{
    /// <summary>
    /// 付款狀態 ID
    /// </summary>
    public int PsId { get; set; }

    /// <summary>
    /// 付款狀態名稱（例：Pending、Paid、Refunded）
    /// </summary>
    public string PaymentStatus1 { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}