// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using TravelLogAPI.Models;

namespace TravelLogAPI.Models
{
    public partial class TravelLogContext
    {
        private ITravelLogContextProcedures _procedures;

        public virtual ITravelLogContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new TravelLogContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ITravelLogContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class TravelLogContextProcedures : ITravelLogContextProcedures
    {
        private readonly TravelLogContext _context;

        public TravelLogContextProcedures(TravelLogContext context)
        {
            _context = context;
        }
        //public async Task<Location> GetLocationByIdAsync(int id)
        //{
        //    var param = new SqlParameter("@Itinerary_ID", id);
        //    var result = await _context.Set<Location>().FromSqlRaw("EXEC getLocation @Itinerary_ID", param).ToListAsync();

        //    return result.FirstOrDefault();
        //}
        public async Task<List<Location>> GetLocationByIdAsync(int id)
        {
            var param = new SqlParameter("@Itinerary_ID", id);
            var sql = "EXEC getLocation @Itinerary_ID";

            var result = await _context.SqlQueryAsync<Location>(sql, new object[] { param });

            return result; // 直接回傳整個 List
        }
    }
}